# Generated by Django 5.0.6 on 2024-07-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_appointment_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checklist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
