# Generated by Django 5.0.6 on 2024-07-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_appointment_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
