# Generated by Django 5.0.6 on 2024-07-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='barber',
        ),
        migrations.DeleteModel(
            name='Barber',
        ),
    ]
