# Generated by Django 5.0.6 on 2024-07-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_appointment_barber_delete_barber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer',
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
