# Generated by Django 5.0.6 on 2024-07-22 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
